In [4]:
import numpy as np
import pandas as pd
import scipy
from sklearn.decomposition import PCA

In [2]:
train = pd.read_csv('close_prices.csv')
train.head()

,date,AXP,BA,CAT,CSCO,CVX,DD,DIS,GE,GS,...,PFE,PG,T,TRV,UNH,UTX,V,VZ,WMT,XOM
0,2013-09-23,76.440002,117.510002,85.029999,24.270000,125.519997,59.409999,64.750000,24.280001,165.250000,...,28.799999,79.279999,34.220001,86.379997,71.820000,109.419998,196.240005,47.980000,76.419998,87.750000
1,2013-09-24,76.070000,119.000000,85.110001,24.139999,124.489998,59.319997,64.320000,24.320000,162.970001,...,28.709999,78.620003,34.090000,85.870003,72.320000,110.000000,193.339996,47.270000,75.750000,87.360001
2,2013-09-25,75.989998,118.510002,84.500000,24.430000,124.070000,59.319997,64.449997,24.230000,162.309998,...,28.490000,77.720001,34.049999,85.980003,71.980003,109.260002,191.559998,46.950001,74.650002,87.139999
3,2013-09-26,76.320000,119.379997,84.199997,23.770000,123.489998,59.509996,65.239998,24.250000,162.289993,...,28.520000,78.050003,34.230000,85.830002,72.160004,109.660004,193.559998,47.669998,74.620003,87.070000
4,2013-09-27,75.889999,118.739998,83.800003,23.330000,122.639999,59.009995,65.190002,24.049999,159.850006,...,28.879999,77.209999,33.980000,85.410004,71.989998,109.360001,193.050003,47.000000,74.360001,86.900002

In [5]:
pca = PCA(n_components=10)

In [7]:
transformed_data = pca.fit_transform(train.iloc[:, 1:])

In [8]:
features = pca.explained_variance_ratio_
print(features)

[0.73897118 0.11007169 0.04995088 0.0287492  0.02215448 0.01931577
 0.00674853 0.00614091 0.00320594 0.00305611]

In [9]:
i = 1
while np.sum(features[:i]) < 0.9:
    i += 1
print(i)

4

In [12]:
file = open('421.txt', 'w')
file.write(str(i))
file.close()

In [15]:
first_component = transformed_data[:, 0]
print(first_component)

[-50.90240358 -52.84690919 -54.61443917 -52.60056628 -52.3701233
 -54.65341197 -52.81257496 -53.6511457  -56.69272698 -54.40265506
 -58.33164549 -61.71626498 -61.31940025 -53.79252445 -50.89263448
 -49.63740755 -52.3876147  -47.47854294 -43.56033499 -42.55928046
 -42.45027087 -42.27124797 -43.25272816 -40.05934481 -38.49726315
 -39.06492263 -38.39304378 -38.40055833 -42.38616981 -39.83057417
 -41.29548604 -40.43554958 -38.49607932 -42.96158052 -38.71252143
 -38.83379331 -39.90606174 -37.58824522 -34.92356725 -32.96232694
 -34.52461722 -36.40345948 -37.22194659 -32.95883861 -30.59159319
 -29.63686919 -27.34513869 -26.90264007 -27.41985754 -28.24277351
 -31.79501246 -31.39698179 -33.14502283 -30.41497345 -30.73495319
 -32.3505575  -30.84313809 -32.84916115 -30.36248061 -29.89452878
 -25.10690112 -19.92249325 -19.83315396 -19.22492561 -17.61370544
 -17.11198746 -15.1995865  -15.45054369 -14.29383343 -12.54655923
 -14.65343703 -14.22824589 -15.48478914 -14.57275272 -14.49575224
 -14.57147435 -14.90094988 -18.08733977 -14.57608896 -12.87297377
 -16.29294039 -11.44328867 -12.16508932  -9.63998802 -15.06290798
 -23.06776353 -26.91995865 -22.87821346 -27.75050687 -24.70186981
 -28.62464535 -34.53355859 -32.18019151 -31.54118404 -27.05721955
 -24.23574502 -24.84846937 -21.57767843 -21.49645104 -21.01277938
 -18.24675263 -17.84705266 -21.1443912  -20.47375337 -19.65361453
 -16.3717419  -16.16580417 -16.53345078 -15.02836209 -13.90497791
 -18.62366746 -13.30830441 -13.96111972 -13.08982225 -11.84534551
 -12.3555285  -13.60961544 -14.45206595 -20.15867531 -20.59032524
 -16.98087035 -14.54161273 -16.23898693 -16.45056292 -16.39898272
 -19.33450937 -22.50633785 -24.95786083 -24.55045335 -25.80870681
 -21.98042132 -21.55387211 -20.98565884 -20.68238159 -26.89934124
 -33.3625941  -33.70208252 -29.37521224 -36.63557107 -42.1231518
 -38.90062677 -36.18661357 -30.7127998  -29.68025039 -29.46266929
 -27.03424951 -27.89075625 -26.90203397 -34.75907319 -34.22818288
 -33.08782875 -32.26694629 -28.91612857 -29.83159366 -28.47322436
 -31.30000272 -27.4578028  -25.32327384 -25.05877927 -22.98536292
 -22.73927287 -24.91826038 -27.49593028 -25.68284515 -24.42656063
 -26.34022596 -23.47844013 -22.9068332  -20.17406385 -16.93633588
 -17.21170203 -15.71847567 -15.46165473 -16.2367055  -16.96171541
 -16.36503919 -15.74082757 -13.99050742 -13.77768144 -12.55544865
 -14.50287058 -16.73839085 -17.43750955 -18.20865984 -16.82078809
 -15.36728487 -15.47414156 -15.65345998 -16.1598975  -17.99133559
 -15.98972901 -15.92400465 -16.1614384  -15.51490347 -13.40740271
 -13.31670597 -11.14233544 -11.82836173 -14.4362593  -13.46204057
 -15.02365619 -13.09803031  -9.6576256   -8.4725706   -9.03101717
 -13.11469727  -9.70864715 -10.52791496  -9.04153791  -9.00917125
  -8.27734177 -13.81777749 -13.60440735 -15.31587494 -14.7827252
 -19.88897618 -19.84265022 -18.34198251 -19.90655938 -19.27429916
 -21.23137883 -18.05792361 -17.93785554 -17.87174581 -16.01146515
 -13.85779827 -15.58499544 -10.81482627  -8.89278244  -6.95524104
  -6.49095709  -6.10142314  -4.9878018   -4.90925115  -4.20285354
  -5.97032984  -6.60414859  -5.24724853  -5.86821182  -5.25308723
  -3.89275277  -2.28846053  -4.60269073  -2.6302005   -3.85220159
  -4.48397326  -3.74501933  -1.42234455  -1.1880331    1.78052875
   1.44944488  -0.87980015  -3.21966268   1.01281668  -4.32400913
  -0.64319502  -1.65804175  -0.80910326  -5.79860391  -5.17789162
  -0.15068684  -1.20933984  -6.25247437  -0.39520452  -6.88664439
 -10.47968447 -13.59298897 -14.21757634 -17.82221527 -15.81508509
  -9.83998444  -3.12784039   6.13095849   2.41988318   8.2716267
  11.21324346  12.43643343  16.19588952  14.75658132  29.26785113
  34.36269946  34.80060943  37.1169061   41.68557862  43.23868399
  43.21133813  43.28326598  43.17987999  44.96916483  45.8370142
  43.57393848  44.59207558  46.17873345  45.71939669  47.41484689
  49.11202723  49.92737338  50.95771219  51.77580923  55.64489937
  54.05350982  56.37369913  57.84166153  58.07756284  61.59733883
  62.22317635  61.85899508  57.14699076  59.07863252  53.41714215
  52.8538358   49.0336456   55.75289834  63.84525082  62.00646233
  65.71912067  66.30084741  67.93823999  67.38152625  67.84780889
  66.77443833  62.85061005  63.04372649  55.7621666   53.25145165
  59.92514065  67.27179699  61.9835951   61.26946241  61.60871606
  55.83691561  54.0250349   57.24214502  57.28249228  60.24216562
  66.36518818  64.35292965  62.99757488  56.84860025  53.24037209
  57.66912036  55.20610164  57.53436284  62.96452996  67.60780205
  74.20625645  71.3050004   68.04197345  70.26879909  71.43526897
  76.34223175  74.85933555  76.32283564  75.6218583   75.40357424
  80.94684893  82.0972697   83.0451399   83.04873001  84.25163568
  81.08530688  88.95395499  85.51436513  83.4410174   84.57974738
  77.97351241  81.46808962  72.45056472  72.45603582  81.29098008
  77.90353421  83.79819948  79.19578947  82.96885933]

In [17]:
index = pd.read_csv('djia_index.csv')
corr_coef = np.corrcoef(first_component, index.iloc[:, 1])[0, 1]
print(corr_coef)

0.9096522193050238

In [18]:
file = open('422.txt', 'w')
file.write(str(round(corr_coef, 2)))
file.close()

In [21]:
new_train = train.iloc[:, 1:]
company = new_train.keys()[pca.components_[0].argmax()]
print(company)

V

In [22]:
file = open('423.txt', 'w')
file.write(company)
file.close()