In [17]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score

In [4]:
data = pd.read_csv('abalone.csv')
data.head()

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [5]:
data['Sex'] = data['Sex'].map(lambda x: 1 if x == 'M' else (-1 if x == 'F' else 0))
data.head()

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,1,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,-1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,1,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,0,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [6]:
y = data.iloc[:, -1]
x = data.iloc[:, :-1]

In [20]:
kf = KFold(n_splits=5, random_state=1, shuffle=True)
    
for i in range(1, 51):
    regr = RandomForestRegressor(n_estimators=i, random_state=1)
    scores = np.array([])
    
    for train_index, test_index in kf.split(x):
        regr.fit(x.loc[train_index], y.loc[train_index])
        prediction = regr.predict(x.loc[test_index])
        scores = np.append(scores, r2_score(y.loc[test_index], prediction))

    current_score = scores.mean()
    print('n_estimators: ', i, ' Score: ', current_score)
    
    if current_score > 0.52:
        f = open('51.txt', 'w')
        f.write(str(i))
        f.close()
        break

n_estimators:  1  Score:  0.10967482068860261
n_estimators:  2  Score:  0.3413000096365689
n_estimators:  3  Score:  0.406433829066129
n_estimators:  4  Score:  0.4447745857536912
n_estimators:  5  Score:  0.46503241426823594
n_estimators:  6  Score:  0.47139595825898917
n_estimators:  7  Score:  0.4766658451893487
n_estimators:  8  Score:  0.4829348394224631
n_estimators:  9  Score:  0.4894370162945041
n_estimators:  10  Score:  0.4954085552428177
n_estimators:  11  Score:  0.4944111155773555
n_estimators:  12  Score:  0.49902817866563326
n_estimators:  13  Score:  0.5030578549564464
n_estimators:  14  Score:  0.5073168234618861
n_estimators:  15  Score:  0.5091809969556578
n_estimators:  16  Score:  0.5114105314179662
n_estimators:  17  Score:  0.5148917747729636
n_estimators:  18  Score:  0.5172203573170132
n_estimators:  19  Score:  0.5198293095329432
n_estimators:  20  Score:  0.51948435033775
n_estimators:  21  Score:  0.520529096463528